### ISSUE TITLE
Error "Unexpected token E" when processing numbers with ExponentPart

### ISSUE THREAD

**Issue by itzg** [tulios/json-viewer#46]
When faced with a JSON document that is:

```
{
    "value": 8.4127988E8
}
```

A `SyntaxError` is reported

```
SyntaxError: Unexpected token E
    at Object.parse (native)
    at chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:1410
    at l (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:2355)
    at p (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:3532)
    at new a (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:2589)
    at r (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:1330)
    at chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:1008
    at o (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:2305)
    at chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:2916
    at MutationObserver.r (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:3929)(anonymous function) @ chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1
```

and only a raw rendering of the document is shown. FYI, using `JSON.parse(...)` directly works fine:

```
> JSON.parse('{"value":8.4127988E8}')
Object {value: 841279880}
```

Using:
* Version 0.9.2 of the extension
* Chrome 44.0.2403.81 beta-m (64-bit) on Windows

**Comment by tulios** [comment]
Really odd, I'll check this up. Thanks!

**Comment by itzg** [comment]
Awesome. And my beloved number made it into the test data :)

**Comment by tulios** [comment]
Many thanks :+1: Version 0.9.3 rolling out!

**Comment by itzg** [comment]
I just confirmed with 0.9.3 that the full document that contained that number is rendering perfectly.

**Comment by tulios** [comment]
:tada:
